/*
Exception Handling
Programda hata varsa calismasina engel olmaz

Try Block:
used to wrap code that might throw an exception.
In this case, it contains the code for
reading user input and performing the division.

Catch Block:
catches any exceptions that might be thrown
during the execution of the try block.
If an exception occurs
(such as entering non-integer values or attempting to divide by zero),
the program prints "Error" to the console instead of crashing.

Potential Exceptions
Format Exception:
Thrown if the user input is not a valid integer.

Divide By Zero Exception:
Thrown if num2 is zero.

Overflow Exception:
Thrown if the entered number is too large or too small
to fit in an int
 */



